package vistas;

import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;
import modelos.Estudiante;

/**
 *
 * @author Joseph && Jhovanny
 */
public class VistaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistro
     */
    public VistaRegistro() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegEstudiante = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        JTxtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        JTxtApellidos = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        JTxtCodigo = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        JTxtCedula = new javax.swing.JTextField();
        lblCarrera = new javax.swing.JLabel();
        JCboCarrera = new javax.swing.JComboBox<>();
        lblSemestre = new javax.swing.JLabel();
        JCboSemestre = new javax.swing.JComboBox<>();
        lblPromedio = new javax.swing.JLabel();
        JTxtPromedio = new javax.swing.JTextField();
        JBtnGuardar = new javax.swing.JButton();
        JBtnEditar = new javax.swing.JButton();
        JBtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" ");
        setModalExclusionType(null);
        setResizable(false);

        lblRegEstudiante.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblRegEstudiante.setText("Registro Estudiantes");

        lblNombre.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        JTxtNombre.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        JTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtNombreKeyTyped(evt);
            }
        });

        lblApellidos.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblApellidos.setText("Apellidos:");

        JTxtApellidos.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        JTxtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtApellidosKeyTyped(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblCodigo.setText("Código:");

        JTxtCodigo.setEditable(false);
        JTxtCodigo.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        lblCedula.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblCedula.setText("Cedula:");

        JTxtCedula.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        JTxtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtCedulaKeyTyped(evt);
            }
        });

        lblCarrera.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblCarrera.setText("Carrera:");

        JCboCarrera.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        JCboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diseño Gráfico", "Periodismo", "Publicidad", "Ingeniería de Software", "Administración de Empresas", "Hotelería y Turismo", "Ingeniería Industrial", "Contaduría Pública" }));

        lblSemestre.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblSemestre.setText("Semestre:");

        JCboSemestre.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        JCboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lblPromedio.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        lblPromedio.setText("Promedio:");

        JTxtPromedio.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        JTxtPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtPromedioKeyTyped(evt);
            }
        });

        JBtnGuardar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        JBtnGuardar.setText("Guardar");

        JBtnEditar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        JBtnEditar.setText("Editar");

        JBtnVolver.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        JBtnVolver.setText("Volver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTxtNombre)
                    .addComponent(JTxtApellidos)
                    .addComponent(JTxtCodigo)
                    .addComponent(JTxtCedula)
                    .addComponent(JCboCarrera, 0, 270, Short.MAX_VALUE)
                    .addComponent(JCboSemestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTxtPromedio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApellidos)
                            .addComponent(lblCodigo)
                            .addComponent(lblCedula)
                            .addComponent(lblCarrera)
                            .addComponent(lblSemestre)
                            .addComponent(lblPromedio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblRegEstudiante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegEstudiante)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JCboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPromedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnGuardar)
                    .addComponent(JBtnVolver)
                    .addComponent(JBtnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtApellidosKeyTyped
        //Crea una variable caracter, en la que reciba el caracter que se esta ingresando
        char validar = evt.getKeyChar();

        //Verifica el tipo del caracter que se esta ingresando
        if (Character.isDigit(validar)) {
            evt.consume();
            //Muestra un mensaje 
            JOptionPane.showMessageDialog(null, "Ingresar solo letras");
        }
    }//GEN-LAST:event_JTxtApellidosKeyTyped

    private void JTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtNombreKeyTyped
        //Crea una variable caracter, en la que reciba el caracter que se esta ingresando
        char validar = evt.getKeyChar();

        //Verifica el tipo del caracter que se esta ingresando
        if (Character.isDigit(validar)) {
            evt.consume();
            //Muestra un mensaje 
            JOptionPane.showMessageDialog(null, "Ingresar solo letras");
        }
    }//GEN-LAST:event_JTxtNombreKeyTyped

    private void JTxtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtCedulaKeyTyped
        //Crea una variable caracter, en la que reciba el caracter que se esta ingresando
        char validar = evt.getKeyChar();

        //Verifica el tipo del caracter que se esta ingresando
        if (Character.isLetter(validar)) {
            evt.consume();
            //Muestra un mensaje 
            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_JTxtCedulaKeyTyped

    private void JTxtPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtPromedioKeyTyped
        char validar = evt.getKeyChar();
        if (JTxtPromedio.getText().length() == 0) {
            if (validar == '0' || validar == '1' || validar == '2' || validar == '3' || validar == '4' || validar == '5') {
                if (validar == '5') {
                    evt.consume();
                    JTxtPromedio.setText("5.0");
                }
            } else {
                //Puede poner aviso acá
                evt.consume();
            }
        } else if (JTxtPromedio.getText().length() == 1) {
            if (validar == '.') {
            } else {
                //Puede poner aviso acá
                evt.consume();
            }
        } else if (JTxtPromedio.getText().length() == 2 && validar != KeyEvent.VK_BACK_SPACE) {
            if (JTxtPromedio.getText().equals("5.")){
                evt.consume();
                JTxtPromedio.setText("5.0");
            }
            if (Character.isDigit(validar)) {
            } else {
                //Puede poner aviso acá
                evt.consume();
            }
        } else {
            //Puede poner aviso acá
            evt.consume();
        }
        
    }//GEN-LAST:event_JTxtPromedioKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaRegistro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBtnEditar;
    public javax.swing.JButton JBtnGuardar;
    public javax.swing.JButton JBtnVolver;
    public javax.swing.JComboBox<String> JCboCarrera;
    public javax.swing.JComboBox<String> JCboSemestre;
    public javax.swing.JTextField JTxtApellidos;
    public javax.swing.JTextField JTxtCedula;
    public javax.swing.JTextField JTxtCodigo;
    public javax.swing.JTextField JTxtNombre;
    public javax.swing.JTextField JTxtPromedio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblRegEstudiante;
    private javax.swing.JLabel lblSemestre;
    // End of variables declaration//GEN-END:variables
}
